const fs = require('fs');
const content = fs.readFileSync('src/pages/SolarCalculator.tsx', 'utf8');

const target1 = `<Button onClick={() => navigator.clipboard.writeText(window.location.href)} className="bg-slate-800 text-white hover:bg-slate-700 border border-slate-700 w-full">                  <Link2 className="mr-2 h-4 w-4" /> Copy Link                </Button>              </div>`;
const replace1 = target1 + `              <div className="mt-4 pt-4 border-t border-slate-800">                <Button onClick={() => {                  if (window.gtag) {                    window.gtag("event", "sizing_to_payback_click", { event_category: "Navigation" });                  }                  window.location.href = "/payback-calculator";                }} className="bg-yellow-500 text-slate-900 hover:bg-yellow-400 font-bold w-full">                  Is it worth it? See Payback vs. Grid →                </Button>              </div>`;

const target2 = `            </div>          </section>        </div>      </div>            <CalculatorFooter`;
const replace2 = `            </div>          </section>        </div>      </div>            <div className="mt-12 bg-white border border-slate-200 rounded-xl p-6 sm:p-8">        <h3 className="text-xl font-bold text-slate-900 mb-4">Formula &amp; Worked Example</h3>        <p className="text-slate-600 mb-4">          The core formula for sizing a solar array ensures the panels can generate a full day's worth of energy during the short window of usable sunlight, while compensating for system losses.        </p>        <div className="bg-slate-50 p-4 rounded-md font-mono text-sm text-slate-800 mb-6 border border-slate-200 overflow-x-auto whitespace-nowrap">          Array Watts = (Daily Wh) ÷ (Peak Sun Hours × System Efficiency %)        </div>        <h4 className="font-bold text-slate-900 mb-2">Example:</h4>        <ul className="space-y-4 text-sm text-slate-700">          <li className="flex items-start">            <span className="font-mono bg-slate-100 px-2 py-1 rounded mr-3 text-slate-800">1</span>            <span>You have a 50W light bulb running 10 hours a day. Daily Demand = <strong>500 Wh/day</strong>.</span>          </li>          <li className="flex items-start">            <span className="font-mono bg-slate-100 px-2 py-1 rounded mr-3 text-slate-800">2</span>            <span>You live in an area with <strong>4.0 Peak Sun Hours</strong> in the winter, and assume <strong>75% efficiency</strong>.</span>          </li>          <li className="flex items-start">            <span className="font-mono bg-slate-100 px-2 py-1 rounded mr-3 text-slate-800">3</span>            <span>Calculation: 500 ÷ (4.0 × 0.75) = 500 ÷ 3 = <strong>166.6 Watts</strong>. You should install at least a 167W solar panel.</span>          </li>        </ul>      </div>      <CalculatorFooter`;

const newContent = content.replace(target1, replace1).replace(target2, replace2);
fs.writeFileSync('src/pages/SolarCalculator.tsx', newContent);
